#include <QtGui/QGuiApplication>
#include <QtQml/QQmlApplicationEngine>
#include <QtQml/QQmlComponent>

#include <QAKCore/actionextension.h>
#include <QAKCore/actionregistry.h>
#include <QAKQuick/quickactioncontext.h>

// Generated by qak_add_action_extension() in the binary directory
#include "core-actions.qak.h"
#include "plugin-actions.qak.h"

using namespace QAK;

int main(int argc, char *argv[]) {
    QGuiApplication a(argc, argv);

    ActionRegistry registry;
    auto coreActionExtension = coreActions();
    auto pluginActionExtension = pluginActions();
    registry.setExtensions({coreActionExtension, pluginActionExtension});

    QuickActionContext context;
    registry.addContext(&context);

    QQmlApplicationEngine engine;
    engine.setInitialProperties({{"context", QVariant::fromValue(&context)}});

    QQmlComponent actionsComponent(&engine, ":/qt/qml/QActionKit/Examples/Quick/actions.qml");
    auto o = actionsComponent.createWithInitialProperties({{"context", QVariant::fromValue(&context)}});

    engine.load(":/qt/qml/QActionKit/Examples/Quick/main.qml");

    registry.updateContext(QAK::AE_Layouts);

    return a.exec();

}
